### ISSUE TITLE
Could not evaluate: undefined method `destroy' for nil:NilClass

### ISSUE THREAD

**Issue by fluential** [larstobi/puppet-dns#1] opened 2012-09-26 12:06 UTC
When creating a new record which does not exist I get: "Could not evaluate: undefined method `destroy' for nil:NilClass", when I tried to modify slightly flush method in dnsrecord I then got:
Could not evaluate: Expected(200) <=> Actual(400 Bad Request) 
XML response "Tried to create resource record set xxxx , type CNAME but it already exists" - I guess that is something related to the way how fog works, would be nice to fix...

Also I had the issue related to this http://projects.puppetlabs.com/issues/15074 , I had to manually add LOAD_PATH to the providers in order to make things work.

Puppet version: 2.7.19-1puppetlabs2 (Ubuntu)

**Comment by larstobi** [comment] 2012-11-19 10:05
Do you have a sample manifest to reproduce the undefined method for nil:NilClass error?

What modifications did you do to the flush method?

**Comment by fluential** [comment] 2012-11-20 10:47
Right, I don't remember exactly what changes I was doing as this was two months ago... but here is the code that i use:

1) The case where record already exist:

dnsrecord {
    'test.fqdn.com.':
        ensure => present,
        value  => '1.2.3.4',
        type   => 'A',
        zone   => 'fqdn.com.',
        ttl    => '61',
        id     => 'xx',
        secret => 'xx',
}

root@puppetmaster-client:~#> puppet apply dns.pp
notice: /Stage[main]//Dnsrecord[test.fqdn.com.]/value: value changed ['ec2-XXX-YYY-ZZZ.compute.amazonaws.com'] to '1.2.3.4'
notice: /Stage[main]//Dnsrecord[test.fqdn.com.]/ttl: ttl changed '60' to '61'
notice: Finished catalog run in 1.53 seconds

2) Case where record DOES NOT exist

dnsrecord {
    'testqwerty.fqdn.com.':
        ensure => present,
        value  => '1.2.3.4',
        type   => 'A',
        zone   => 'fqdn.com.',
        ttl    => '61',
        id     => 'xx',
        secret => 'xx',
}

root@puppetmaster-client:~#> puppet apply dns.pp
notice: /Stage[main]//Dnsrecord[testqwerty.fqdn.com.]/ensure: created
err: /Stage[main]//Dnsrecord[testqwerty.fqdn.com.]: Could not evaluate: undefined method `destroy' for nil:NilClass
notice: Finished catalog run in 1.27 seconds

**Comment by larstobi** [comment] 2012-11-20 12:12
Thanks, I am able to reproduce this reliably.

**Comment by rharper-aimia** [comment] 2013-04-12 09:21
Hi did this ever get resolved? I am experiencing the same issue any resolution to this would be great

**Comment by fluential** [comment] 2013-04-24 14:24
I don't think so

**Comment by larstobi** [comment] 2013-04-26 15:08
I haven't had the time to maintain this plugin properly. I have found that the bug was introduced by the flush method in the provider. By removing the entire flush method, the bug doesn't show up, but since the IP address is a parameter instead of a property, it will not update changes in IP address.

I'll gladly accept patches, of course.

By the way, the puppet-dns plugin by masterzen is better than this one, and seems to work well, so I suggest you switch to it.

**Comment by fluential** [comment] 2013-04-26 15:17
Right, I didn't have time to dive into ruby either... thanks for the info though. Have a nice day.

**Comment by larstobi** [comment] 2015-09-10 07:22
Fixed by 08471949321422d45f6d946ef79a55abd846bab4.

**Closed as completed by larstobi** 2015-09-10 07:22 UTC
